### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by ritapas** [SondagesPro/maintenanceMode#2]
hello,
sorry if i posted this on your site.
I think there is a typo in the english message for maintenance mode
"This website are on maintenance mode" shouldn’t be "This website is on maintenance mode."?

**Comment by Shnoulle** [comment]
Fixed in https://gitlab.com/SondagesPro/coreAndTools/maintenanceMode/commit/7229efeb12a58518e86a0543ea5248a2eacd109e I set up mirroring.

Else : https://translate.sondages.pro/projects/maintenancemode/

**Comment by Shnoulle** [comment]
Mirror are up to date
