### ISSUE TITLE
I have a problem with the renderMessage plugin in IIS, windows Server 2019 (LS: v3.25.19)

### ISSUE THREAD

**Issue by alorenc** [SondagesPro/maintenanceMode#3]
_Unable to find template "./subviews/content/alert.twig" (looked into: D:\inetpub\wwwroot\xxx\themes\survey\custom\views, D:\inetpub\wwwroot\xxx\themes\survey\vanilla\views, D:\inetpub\wwwroot\xxx\application/views)._

During deployment, the error did not occur, but was revealed after resetting the theme configuration.
I don't know if it's a plugin bug or a Limesurvey bug.

In the local environment (Windows 10) the error does not occur, in Windows Server 2019 the problem occurs. I guess this might be related to the permission scope of the folders. Do I need to give special permissions to the plug-in folder with views?

This is exactly where it happens: **maintenanceMode::_endDuToMaintenance()** calls 
`\renderMessage\messageHelper::renderAlert($message,'warning');`

and this is exactly in messageHelper :: render crashes on:
`Yii::app()->twigRenderer->renderTemplateFromFile('layout_'.$layout.'.twig', $renderData,false);`

**Comment by alorenc** [comment]
Fixed: the problem was with force_xmlsettings_for_survey = true.

Since we wanted to force reloading the theme without resetting in the test environment, we forgot to disable this option.

Although it would be good to add a security feature in the plug that would display a page error, but with a note in the logs what caused it.

**Comment by Shnoulle** [comment]
I still using this plugin on 3.27.26 on a windows IIS server,

The «looked into: D:\inetpub\wwwroot\xxx\themes\survey\custom\views, D:\inetpub\wwwroot\xxx\themes\survey\vanilla\views, D:\inetpub\wwwroot\xxx\application/views» are not complete here , 
Lack of view from maintenance mode : https://gitlab.com/SondagesPro/coreAndTools/maintenanceMode/-/blob/master/maintenanceMode.php#L108

In my opinion : you have another things that break this plugin part.

**Comment by Shnoulle** [comment]
> Although it would be good to add a security feature in the plug that would display a page error, but with a note in the logs what caused it.

Impossible to check if something other broke.

I never have to use `force_xmlsettings_for_survey`
